const METHODS=['azras','wood_frame','rc_frame'];
const LABELS={azras:'AZRAS',wood_frame:'2x6 Timber',rc_frame:'RC Frame'};
const COLORS={azras:'#783278',wood_frame:'#5f7895',rc_frame:'#8c6f52'};
const I18N={
 ja:{eyebrow:'AZRAS COMPARE — ONLINE DEMO',title:'3工法を、検証済みサンプルデータで比較',lead:'デスクトップ版AZRASが保存した Core Project JSON Schema 3.0 を読み取る、計算を行わないRead-only Viewerです。',tabRegional:'7都市 地域比較',tabDetail:'詳細比較（元Project）',tabAbout:'データについて',regionalTitle:'7都市の8760時間解析結果',regionalNote:'各地域派生JSONの module10_snapshot を使用。年間エネルギー・年間運用CO₂・電力CO₂係数を工法横断で比較します。',cityLabel:'都市',energyChart:'年間エネルギー消費量',co2Chart:'年間運用CO₂排出量',city:'都市',detailTitle:'元Project JSONによる詳細比較',detailNote:'Module 4/5/6を保存した元Project JSONを使用します。地域派生JSONにはこれらのModuleが含まれないため、7都市の値としては表示しません。',lifecycleChart:'累積ライフサイクルCO₂',cfChart:'現在価値累積CF（終価除外）',period:'期間',years:'年',aboutTitle:'このデモの位置付け',about1:'このページはAZRAS Compare v1.1.37の「Read-only comparison viewer」という契約に沿って構成しています。元JSONへ書き戻しません。',about2:'ブラウザ内では建物計算・8760時間解析・LCA・事業性計算を再実行しません。表示値はAZRAS本体が保存したサンプルJSONから読み取ります。',disclaimer:'デモデータです。設計・施工・投資判断の前に、利用者自身で計算結果を確認してください。'},
 en:{eyebrow:'AZRAS COMPARE — ONLINE DEMO',title:'Compare three construction methods using verified sample data',lead:'A read-only viewer for Core Project JSON Schema 3.0 saved by the AZRAS desktop applications. No building analysis is recalculated in the browser.',tabRegional:'7-City Regional',tabDetail:'Detailed (Base Project)',tabAbout:'About the Data',regionalTitle:'8760-hour results across seven cities',regionalNote:'Uses module10_snapshot in each regional derivative JSON to compare annual energy, operational CO₂, and grid CO₂ factors.',cityLabel:'City',energyChart:'Annual energy use',co2Chart:'Annual operational CO₂',city:'City',detailTitle:'Detailed comparison using base Project JSON',detailNote:'Uses base Project JSON with saved Module 4/5/6 results. Regional derivative JSON does not contain those modules, so these values are not presented as seven-city results.',lifecycleChart:'Cumulative lifecycle CO₂',cfChart:'Cumulative present-value cash flow (terminal value excluded)',period:'Period',years:'years',aboutTitle:'What this demo is',about1:'This page follows the AZRAS Compare v1.1.37 contract: “Read-only comparison viewer.” It never writes back to source JSON.',about2:'The browser does not rerun building calculations, 8760-hour analysis, LCA, or business analysis. Values are read from sample JSON saved by the AZRAS desktop system.',disclaimer:'Demo data only. Users must verify calculation results before design, construction, or investment decisions.'}
};
let lang='ja', manifest, regional={}, base={};
const n=v=>{const x=Number(v);return Number.isFinite(x)?x:null};
const fmt=(v,d=1)=>v==null?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d});
const get=(o,path,fb=null)=>path.reduce((x,k)=>x&&x[k]!==undefined?x[k]:null,o)??fb;
function savedModule(p,k){const m=get(p,['module_outputs',k]); if(!m||typeof m!=='object')return null; const meta=m._meta||{}; const s=String(meta.status||'').toLowerCase(); return ['saved','calculated','final','complete','completed','auto_updated'].includes(s)||Object.keys(meta).length===0?m:null}
function annual(p){return get(p,['regional_analysis','module10_snapshot','annual'],{})}
function monthly(p){return get(p,['regional_analysis','module10_snapshot','monthly'],[])}
function regionalMetrics(p){const a=annual(p);return {energy:n(a.total_use_kWh),co2:n(a.operational_co2_kg),factor:n(a.electricity_co2_factor_kg_per_kWh)}}
function lifecycle(p){const m4=savedModule(p,'module4'), a=annual(p); const bop=n(a.operational_co2_kg); if(!m4||bop==null)return[]; const rows=m4.annual_timeline, st=m4.settings||{}; if(!Array.isArray(rows))return[]; const gr=(n(st.grid_co2_change_pct_per_year)||0)/100, or=(n(st.operational_change_pct_per_year)||0)/100; let cum=0,out=[]; for(let i=0;i<rows.length;i++){const r=rows[i], y=n(r.year);if(y==null||y!==i)return[];const op=y===0?0:bop*Math.pow(1+gr,y-1)*Math.pow(1+or,y-1); cum+=op+(n(r.embodied_co2_kg)||0)+(n(r.demolition_co2_kg)||0)-(n(r.credit_co2_kg)||0);out.push([y,cum]);}return out}
function cashflow(p,nominal=false){const m=savedModule(p,'module6');if(!m||!Array.isArray(m.cashflow))return[];const s=m.summary||{}, set=get(m,['_input_snapshot','settings'],{});let init=n(s.initial_total_investment);if(init==null)init=n(s.construction_cost);let dr=n(set.discount_rate_percent);if(dr==null)dr=n(set.discount_rate);if(dr!=null&&Math.abs(dr)>1)dr/=100;if(init==null||(!nominal&&(dr==null||dr<=-1)))return[];let cum=-init,out=[[0,cum]],exp=1;for(const r of m.cashflow){const y=n(r.year),u=n(r.unlevered_cash_flow??r.before_tax_cash_flow),term=n(r.terminal_sale_proceeds)||0;if(y!==exp||u==null)return[];const h=u-term;cum+=nominal?h:h/Math.pow(1+dr,y);out.push([y,cum]);exp++;}return out}
function constructionCost(p){const m5=savedModule(p,'module5');let v=n(get(m5||{},['summary','total_construction_cost']));if(v==null){const m6=savedModule(p,'module6');v=n(get(m6||{},['summary','construction_cost']))}return v}
function valueAt(series,y){const r=series.find(x=>x[0]===y);return r?r[1]:null}
function payback(series){for(let i=0;i<series.length;i++)if(series[i][1]>=0)return series[i][0];return null}
async function load(){manifest=await fetch('data/manifest.json').then(r=>r.json());for(const m of METHODS){regional[m]={};for(const c of manifest.cities){regional[m][c.token]=await fetch(manifest.methods[m].regional[c.token]).then(r=>r.json())}base[m]=await fetch(manifest.methods[m].base).then(r=>r.json())}initUI();document.getElementById('loadStatus').textContent=lang==='ja'?'Schema 3.0 サンプル読込済み':'Schema 3.0 samples loaded'}
function initUI(){const sel=document.getElementById('citySelect');manifest.cities.forEach(c=>sel.add(new Option(c.label,c.token)));sel.value='Sapporo';sel.onchange=renderRegional;document.getElementById('co2Year').onchange=renderDetail;document.getElementById('cfYear').onchange=renderDetail;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')});document.getElementById('langBtn').onclick=()=>{lang=lang==='ja'?'en':'ja';document.documentElement.lang=lang;document.getElementById('langBtn').textContent=lang==='ja'?'EN':'日本語';applyI18n();renderRegional();renderDetail()};applyI18n();renderRegional();renderDetail()}
function applyI18n(){document.querySelectorAll('[data-i18n]').forEach(e=>{const v=I18N[lang][e.dataset.i18n];if(v)e.textContent=v})}
function metricCard(m,rows){return `<article class="metric-card"><div class="method">${LABELS[m]}</div>${rows.map(([k,v])=>`<div class="metric-row"><span>${k}</span><strong>${v}</strong></div>`).join('')}</article>`}
function renderRegional(){const token=document.getElementById('citySelect').value;const ms=Object.fromEntries(METHODS.map(m=>[m,regionalMetrics(regional[m][token])]));const factors=METHODS.map(m=>ms[m].factor).filter(x=>x!=null);const ok=factors.length===3&&factors.every(x=>Math.abs(x-factors[0])<1e-12);const audit=document.getElementById('factorAudit');audit.className='audit'+(ok?'':' warn');audit.textContent=ok?(lang==='ja'?`電力CO₂係数整合監査：OK（${factors[0]} kg-CO₂/kWh）`:`Grid CO₂ factor audit: OK (${factors[0]} kg-CO₂/kWh)`):(lang==='ja'?'電力CO₂係数整合監査：要確認':'Grid CO₂ factor audit: check required');document.getElementById('regionalCards').innerHTML=METHODS.map(m=>metricCard(m,[[lang==='ja'?'年間エネルギー':'Annual energy',fmt(ms[m].energy,1)+' kWh/yr'],[lang==='ja'?'年間運用CO₂':'Operational CO₂',fmt(ms[m].co2/1000,3)+' t-CO₂/yr'],[lang==='ja'?'電力CO₂係数':'Grid CO₂ factor',fmt(ms[m].factor,3)+' kg/kWh']])).join('');bars('energyBars',ms,'energy',' kWh/yr',1);const ms2=Object.fromEntries(METHODS.map(m=>[m,{co2:ms[m].co2/1000}]));bars('co2Bars',ms2,'co2',' t-CO₂/yr',3);renderMatrix()}
function bars(id,ms,key,unit,d){const max=Math.max(...METHODS.map(m=>ms[m][key]||0),1);document.getElementById(id).innerHTML=METHODS.map(m=>`<div class="bar-row"><strong>${LABELS[m]}</strong><div class="bar-track"><div class="bar-fill" style="width:${100*(ms[m][key]||0)/max}%"></div></div><span class="bar-value">${fmt(ms[m][key],d)}${unit}</span></div>`).join('')}
function renderMatrix(){const body=document.getElementById('cityMatrix');body.innerHTML=manifest.cities.map(c=>{const vals=METHODS.map(m=>regionalMetrics(regional[m][c.token]).energy);return `<tr><td>${c.label}</td>${vals.map(v=>`<td>${fmt(v,1)} kWh</td>`).join('')}</tr>`}).join('')}
function renderDetail(){const cy=Number(document.getElementById('co2Year').value), fy=Number(document.getElementById('cfYear').value);document.getElementById('detailCards').innerHTML=METHODS.map(m=>{const p=base[m], lc=lifecycle(p), cf=cashflow(p), nom=cashflow(p,true), cost=constructionCost(p), city=get(p,['common','city'],'');return metricCard(m,[[lang==='ja'?'元Project所在地':'Base project location',city],[lang==='ja'?'建設費':'Construction cost',fmt(cost,0)+' JPY'],[`${cy}${lang==='ja'?'年累積CO₂':'-yr cumulative CO₂'}`,fmt((valueAt(lc,cy)||0)/1000,1)+' t-CO₂'],[lang==='ja'?'単純投資回収':'Simple payback',(payback(nom)??'—')+(lang==='ja'?' 年':' yr')],[`${fy}${lang==='ja'?'年現在価値CF':'-yr present-value CF'}`,fmt(valueAt(cf,fy),0)+' JPY']])}).join('');lineChart('lifecycleLines',Object.fromEntries(METHODS.map(m=>[m,lifecycle(base[m]).filter(x=>x[0]<=cy).map(x=>[x[0],x[1]/1000])])),lang==='ja'?'年':'Year','t-CO₂');lineChart('cashflowLines',Object.fromEntries(METHODS.map(m=>[m,cashflow(base[m]).filter(x=>x[0]<=fy)])),lang==='ja'?'年':'Year','JPY')}
function lineChart(id,series,xlabel,unit){const W=920,H=360,pad={l:76,r:24,t:24,b:50};const all=Object.values(series).flat();if(!all.length){document.getElementById(id).innerHTML='—';return}const xs=all.map(x=>x[0]),ys=all.map(x=>x[1]);let xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(0,...ys),ymax=Math.max(0,...ys);if(ymax===ymin)ymax=ymin+1;const X=x=>pad.l+(x-xmin)/(xmax-xmin||1)*(W-pad.l-pad.r),Y=y=>H-pad.b-(y-ymin)/(ymax-ymin)*(H-pad.t-pad.b);let s=`<svg viewBox="0 0 ${W} ${H}" role="img">`;for(let i=0;i<=5;i++){const yy=pad.t+i*(H-pad.t-pad.b)/5, val=ymax-i*(ymax-ymin)/5;s+=`<line x1="${pad.l}" y1="${yy}" x2="${W-pad.r}" y2="${yy}" stroke="#e6dfe8"/><text x="${pad.l-8}" y="${yy+4}" text-anchor="end" font-size="11" fill="#706773">${short(val)}</text>`}s+=`<line x1="${pad.l}" y1="${Y(0)}" x2="${W-pad.r}" y2="${Y(0)}" stroke="#a89dad"/>`;for(const m of METHODS){const pts=(series[m]||[]).map(([x,y])=>`${X(x)},${Y(y)}`).join(' ');s+=`<polyline points="${pts}" fill="none" stroke="${COLORS[m]}" stroke-width="3"/>`}s+=`<text x="${W/2}" y="${H-12}" text-anchor="middle" font-size="12">${xlabel}</text><text x="16" y="${H/2}" transform="rotate(-90 16 ${H/2})" text-anchor="middle" font-size="12">${unit}</text></svg><div class="legend">${METHODS.map(m=>`<span><i style="background:${COLORS[m]}"></i>${LABELS[m]}</span>`).join('')}</div>`;document.getElementById(id).innerHTML=s}
function short(v){const a=Math.abs(v);if(a>=1e9)return (v/1e9).toFixed(1)+'B';if(a>=1e6)return (v/1e6).toFixed(1)+'M';if(a>=1e3)return (v/1e3).toFixed(0)+'k';return v.toFixed(0)}
load().catch(e=>{console.error(e);document.getElementById('loadStatus').textContent='Load error: '+e.message;document.querySelector('.dot').style.background='#b00020'});
